/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package surigamesdao;

import Presentation.AddClientes;
import Presentation.ListClientes;
import Presentation.ListVendas;
import Presentation.AddVendas;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import Presentation.AddJogos;
import Presentation.ListJogos;

/**
 *
 * @author Diego
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ContactEditorUI
     */
    public MenuPrincipal() {
        initComponents();
    }
    
    private void setMaximumSize(JInternalFrame jInternalFrame) {
        try {
            jInternalFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFornecedores = new javax.swing.JMenu();
        BtnAddVenda = new javax.swing.JMenuItem();
        BtnListarVenda = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        BtnAddClientes = new javax.swing.JMenuItem();
        BtnListarClientes = new javax.swing.JMenuItem();
        MenuJogos = new javax.swing.JMenu();
        BtnAddJogo = new javax.swing.JMenuItem();
        BtnListarJogos = new javax.swing.JMenuItem();
        BtnListarJogosVendidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuriGames - Gerenciador de Vendas de Jogos");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        MenuFornecedores.setText("Vendas");

        BtnAddVenda.setText("Fazer Nova Venda");
        BtnAddVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddVendaActionPerformed(evt);
            }
        });
        MenuFornecedores.add(BtnAddVenda);

        BtnListarVenda.setText("Listar Vendas");
        BtnListarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarVendaActionPerformed(evt);
            }
        });
        MenuFornecedores.add(BtnListarVenda);

        jMenuBar1.add(MenuFornecedores);

        MenuClientes.setText("Clientes");

        BtnAddClientes.setText("Adicionar Cliente");
        BtnAddClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddClientesActionPerformed(evt);
            }
        });
        MenuClientes.add(BtnAddClientes);
        BtnAddClientes.getAccessibleContext().setAccessibleDescription("");

        BtnListarClientes.setText("Listar Clientes");
        BtnListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarClientesActionPerformed(evt);
            }
        });
        MenuClientes.add(BtnListarClientes);

        jMenuBar1.add(MenuClientes);

        MenuJogos.setText("Jogos");

        BtnAddJogo.setText("Adicionar Jogo");
        BtnAddJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddJogoActionPerformed(evt);
            }
        });
        MenuJogos.add(BtnAddJogo);

        BtnListarJogos.setText("Listar Jogos");
        BtnListarJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarJogosActionPerformed(evt);
            }
        });
        MenuJogos.add(BtnListarJogos);

        BtnListarJogosVendidos.setText("Listar Jogos Vendidos");
        BtnListarJogosVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarJogosVendidosActionPerformed(evt);
            }
        });
        MenuJogos.add(BtnListarJogosVendidos);

        jMenuBar1.add(MenuJogos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddVendaActionPerformed
        AddVendas addFornecedores = new AddVendas();
        PanelPrincipal.add(addFornecedores);
        addFornecedores.setVisible(true);
    }//GEN-LAST:event_BtnAddVendaActionPerformed

    private void BtnAddClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddClientesActionPerformed
        AddClientes addClientes = new AddClientes();
        PanelPrincipal.add(addClientes);
        addClientes.setVisible(true);
        //setMaximumSize(addClientes);
    }//GEN-LAST:event_BtnAddClientesActionPerformed

    private void BtnListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarClientesActionPerformed
        ListClientes listarClientes = new ListClientes();
        PanelPrincipal.add(listarClientes);
        listarClientes.setVisible(true);
        setMaximumSize(listarClientes);
    }//GEN-LAST:event_BtnListarClientesActionPerformed

    private void BtnListarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarVendaActionPerformed
        ListVendas listarVendas = new ListVendas();
        PanelPrincipal.add(listarVendas);
        listarVendas.setVisible(true);
        setMaximumSize(listarVendas);
    }//GEN-LAST:event_BtnListarVendaActionPerformed

    private void BtnAddJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddJogoActionPerformed
        AddJogos addJogos = new AddJogos();
        PanelPrincipal.add(addJogos);
        addJogos.setVisible(true);
        //setMaximumSize(addJogos);
    }//GEN-LAST:event_BtnAddJogoActionPerformed

    private void BtnListarJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarJogosActionPerformed
        ListJogos listarJogos = new ListJogos();
        PanelPrincipal.add(listarJogos);
        listarJogos.setVisible(true);
        setMaximumSize(listarJogos);
    }//GEN-LAST:event_BtnListarJogosActionPerformed

    private void BtnListarJogosVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarJogosVendidosActionPerformed
        ListVendas listarVendas = new ListVendas();
        PanelPrincipal.add(listarVendas);
        listarVendas.setVisible(true);
        setMaximumSize(listarVendas);
    }//GEN-LAST:event_BtnListarJogosVendidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnAddClientes;
    private javax.swing.JMenuItem BtnAddJogo;
    private javax.swing.JMenuItem BtnAddVenda;
    private javax.swing.JMenuItem BtnListarClientes;
    private javax.swing.JMenuItem BtnListarJogos;
    private javax.swing.JMenuItem BtnListarJogosVendidos;
    private javax.swing.JMenuItem BtnListarVenda;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuFornecedores;
    private javax.swing.JMenu MenuJogos;
    private javax.swing.JDesktopPane PanelPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
